'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppData,Bitacora,Cliente,Contratista,Cotizacion,Factura,Movimiento,Proyecto} from '@/lib/types';
import {loadData,saveData,seedData} from '@/lib/store';
import {Building2,Users,FileText,FolderKanban,NotebookPen,WalletCards,ReceiptText,CircleDollarSign,HardHat,Landmark,BarChart3,Settings,Menu,X,Plus,Search,Printer,Trash2,ChevronRight,TrendingUp,Clock,CheckCircle2,LogOut,Moon,Sun,ShieldCheck,ArrowRight} from 'lucide-react';

type Section='dashboard'|'clientes'|'cotizaciones'|'proyectos'|'bitacoras'|'cobros'|'facturas'|'gastos'|'contratistas'|'caja'|'reportes'|'config';
const money=(n:number)=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP',maximumFractionDigits:2}).format(n);
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const today=()=>new Date().toISOString().slice(0,10);

export default function ERPApp(){
 const [data,setData]=useState<AppData>(seedData); const [ready,setReady]=useState(false); const [section,setSection]=useState<Section>('dashboard'); const [open,setOpen]=useState(false); const [query,setQuery]=useState('');
 const [logged,setLogged]=useState(false); const [theme,setTheme]=useState<'light'|'dark'>('light');
 useEffect(()=>{setData(loadData());setReady(true);setLogged(localStorage.getItem('cp-auth')==='1');setTheme((localStorage.getItem('cp-theme') as 'light'|'dark')||'light')},[]); useEffect(()=>{if(ready)saveData(data)},[data,ready]);
 useEffect(()=>{if(ready){localStorage.setItem('cp-theme',theme);document.documentElement.dataset.theme=theme}},[theme,ready]);
 const ingresos=data.movimientos.filter(m=>m.tipo==='cobro').reduce((a,b)=>a+b.monto,0); const gastos=data.movimientos.filter(m=>m.tipo==='gasto').reduce((a,b)=>a+b.monto,0); const contratado=data.proyectos.reduce((a,b)=>a+b.monto,0); const porCobrar=Math.max(0,contratado-ingresos); const caja=data.cuentas.reduce((a,b)=>a+b.saldoInicial,0)+ingresos-gastos;
 const menu:[Section,string,any][]=[['dashboard','Dashboard',Building2],['clientes','Clientes',Users],['cotizaciones','Cotizaciones',FileText],['proyectos','Proyectos',FolderKanban],['bitacoras','Bitácoras',NotebookPen],['cobros','Cobros y avances',WalletCards],['facturas','Facturación',ReceiptText],['gastos','Gastos',CircleDollarSign],['contratistas','Contratistas',HardHat],['caja','Caja y bancos',Landmark],['reportes','Reportes',BarChart3],['config','Configuración',Settings]];
 const go=(s:Section)=>{setSection(s);setOpen(false);setQuery('')};
 if(!ready)return <div className="boot"><div className="boot-ring"/><b>CONSTRUPLATA</b></div>;
 if(!logged)return <Login onLogin={()=>{localStorage.setItem('cp-auth','1');setLogged(true)}}/>;
 return <div className={`app-shell ${theme==='dark'?'dark':''}` }>
  <aside className={open?'sidebar open':'sidebar'}><div className="brand"><div className="brand-logo"><img src="/logo-construplata.jpg" alt="CONSTRUPLATA"/></div><div><b>CONSTRUPLATA</b><span>Control & Ingeniería</span></div><button className="icon mobile" onClick={()=>setOpen(false)}><X size={20}/></button></div><nav>{menu.map(([id,label,I])=><button key={id} className={section===id?'nav active':'nav'} onClick={()=>go(id)}><I size={19}/><span>{label}</span></button>)}</nav><div className="side-foot"><span>Versión 1.0</span><small>Datos guardados en este navegador</small></div></aside>
  <main className="main"><header className="topbar"><button className="icon mobile" onClick={()=>setOpen(true)}><Menu/></button><div><h1>{menu.find(x=>x[0]===section)?.[1]}</h1><p>Control administrativo y financiero</p></div><div className="top-actions"><button className="icon top-icon" title="Cambiar tema" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..."/></div><div className="avatar">JC</div><button className="icon top-icon logout" title="Cerrar sesión" onClick={()=>{localStorage.removeItem('cp-auth');setLogged(false)}}><LogOut size={18}/></button></div></header>
  <div className="content">
   {section==='dashboard'&&<Dashboard data={data} ingresos={ingresos} gastos={gastos} contratado={contratado} porCobrar={porCobrar} caja={caja} go={go}/>} 
   {section==='clientes'&&<Clientes data={data} setData={setData} query={query}/>} 
   {section==='cotizaciones'&&<Cotizaciones data={data} setData={setData} query={query}/>} 
   {section==='proyectos'&&<Proyectos data={data} setData={setData} query={query}/>} 
   {section==='bitacoras'&&<Bitacoras data={data} setData={setData} query={query}/>} 
   {section==='cobros'&&<Movimientos data={data} setData={setData} tipo="cobro" query={query}/>} 
   {section==='facturas'&&<Facturas data={data} setData={setData} query={query}/>} 
   {section==='gastos'&&<Movimientos data={data} setData={setData} tipo="gasto" query={query}/>} 
   {section==='contratistas'&&<Contratistas data={data} setData={setData} query={query}/>} 
   {section==='caja'&&<Caja data={data} setData={setData}/>} 
   {section==='reportes'&&<Reportes data={data}/>} 
   {section==='config'&&<Configuracion data={data} setData={setData}/>} 
  </div></main>{open&&<div className="overlay" onClick={()=>setOpen(false)}/>}</div>
}

function Login({onLogin}:{onLogin:()=>void}){
 const [email,setEmail]=useState('admin@construplata.com'); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(email.toLowerCase()==='admin@construplata.com'&&password==='Admin123*'){setError('');onLogin()}else setError('Correo o contraseña incorrectos')};
 return <div className="login-page">
  <div className="login-orb orb-a"/><div className="login-orb orb-b"/>
  <section className="login-showcase">
   <div className="showcase-brand"><img src="/logo-construplata.jpg" alt="CONSTRUPLATA"/><span>CONSTRUPLATA</span></div>
   <div className="showcase-copy"><span className="login-kicker">ERP DE CONSTRUCCIÓN</span><h1>Control total.<br/><em>Decisiones claras.</em></h1><p>Administra cotizaciones, proyectos, bitácoras y finanzas desde un único centro de control diseñado para ingeniería civil.</p><div className="showcase-chips"><span>Proyectos</span><span>Finanzas</span><span>Bitácoras</span></div></div>
   <div className="showcase-foot">Gestión inteligente para construir mejor.</div>
  </section>
  <section className="login-panel"><form className="login-card" onSubmit={submit}>
   <div className="login-mobile-logo"><img src="/logo-construplata.jpg" alt="CONSTRUPLATA"/></div>
   <div className="secure-badge"><ShieldCheck size={16}/> Acceso seguro</div><h2>Bienvenido</h2><p>Ingresa a tu centro de control empresarial.</p>
   <label>Correo electrónico<input autoFocus type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="correo@empresa.com"/></label>
   <label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>
   {error&&<div className="login-error">{error}</div>}
   <button className="login-button" type="submit">Entrar al sistema <ArrowRight size={19}/></button>
   <div className="demo-access"><b>Acceso inicial</b><span>admin@construplata.com</span><span>Admin123*</span></div>
   <small>© 2026 CONSTRUPLATA SRL · República Dominicana</small>
  </form></section>
 </div>
}

function Dashboard({data,ingresos,gastos,contratado,porCobrar,caja,go}:{data:AppData;ingresos:number;gastos:number;contratado:number;porCobrar:number;caja:number;go:(s:Section)=>void}){
 const cards=[['Monto contratado',contratado,TrendingUp],['Cobrado a clientes',ingresos,CheckCircle2],['Gastos registrados',gastos,ReceiptText],['Balance por cobrar',porCobrar,Clock],['Disponible estimado',caja,Landmark]] as const;
 return <><div className="hero"><div><span className="eyebrow">Resumen general</span><h2>Buenos días, CONSTRUPLATA</h2><p>Así marcha la empresa y sus trabajos actualmente.</p></div><button className="primary" onClick={()=>go('cotizaciones')}><Plus size={18}/> Nueva cotización</button></div><div className="stats">{cards.map(([l,v,I])=><div className="stat" key={l}><div className="stat-icon"><I size={21}/></div><span>{l}</span><b>{money(v)}</b></div>)}</div><div className="grid2"><section className="panel"><div className="panel-head"><div><h3>Proyectos activos</h3><p>Avance físico y situación financiera</p></div><button className="link" onClick={()=>go('proyectos')}>Ver todos <ChevronRight size={16}/></button></div>{data.proyectos.length?data.proyectos.slice(0,5).map(p=>{const cob=data.movimientos.filter(m=>m.tipo==='cobro'&&m.proyectoId===p.id).reduce((a,b)=>a+b.monto,0);return <div className="project-row" key={p.id}><div><b>{p.nombre}</b><span>{p.estado} · {money(cob)} cobrado</span></div><div className="progress-wrap"><span>{p.avanceFisico}%</span><div className="progress"><i style={{width:`${p.avanceFisico}%`}}/></div></div></div>}):<Empty/>}</section><section className="panel"><div className="panel-head"><div><h3>Actividad reciente</h3><p>Últimos movimientos registrados</p></div></div>{data.movimientos.slice(-6).reverse().map(m=><div className="activity" key={m.id}><div className={m.tipo==='cobro'?'dot green':'dot orange'}/><div><b>{m.concepto}</b><span>{m.fecha} · {m.metodo}</span></div><strong>{m.tipo==='cobro'?'+':'-'}{money(m.monto)}</strong></div>)}</section></div></>
}

function Clientes({data,setData,query}:{data:AppData;setData:(d:AppData)=>void;query:string}){const [show,setShow]=useState(false);const [f,setF]=useState({nombre:'',rnc:'',telefono:'',email:'',direccion:''}); const items=data.clientes.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())); const add=()=>{if(!f.nombre)return;const n:Cliente={id:uid('cli'),...f,creado:today()};setData({...data,clientes:[...data.clientes,n]});setF({nombre:'',rnc:'',telefono:'',email:'',direccion:''});setShow(false)};return <Module title="Clientes" subtitle="Expediente, contactos y balance de cada cliente" action="Nuevo cliente" onAction={()=>setShow(true)}>{show&&<FormCard title="Registrar cliente" close={()=>setShow(false)}><FormGrid><Input label="Nombre o razón social" value={f.nombre} onChange={v=>setF({...f,nombre:v})}/><Input label="RNC/Cédula" value={f.rnc} onChange={v=>setF({...f,rnc:v})}/><Input label="Teléfono" value={f.telefono} onChange={v=>setF({...f,telefono:v})}/><Input label="Correo" value={f.email} onChange={v=>setF({...f,email:v})}/><Input label="Dirección" value={f.direccion} onChange={v=>setF({...f,direccion:v})}/></FormGrid><Save onClick={add}/></FormCard>}<Table heads={['Cliente','RNC/Cédula','Teléfono','Correo','Proyectos','Acciones']}>{items.map(c=><tr key={c.id}><td><b>{c.nombre}</b><small>{c.direccion}</small></td><td>{c.rnc||'—'}</td><td>{c.telefono||'—'}</td><td>{c.email||'—'}</td><td>{data.proyectos.filter(p=>p.clienteId===c.id).length}</td><td><Delete onClick={()=>setData({...data,clientes:data.clientes.filter(x=>x.id!==c.id)})}/></td></tr>)}</Table></Module>}

function Cotizaciones({data,setData,query}:{data:AppData;setData:(d:AppData)=>void;query:string}){const [show,setShow]=useState(false);const [f,setF]=useState({clienteId:data.clientes[0]?.id||'',proyecto:'',descripcion:'',subtotal:'',itbis:false}); const add=()=>{const n:Cotizacion={id:uid('cot'),numero:`COT-${String(data.cotizaciones.length+1).padStart(4,'0')}`,fecha:today(),clienteId:f.clienteId,proyecto:f.proyecto,descripcion:f.descripcion,subtotal:Number(f.subtotal),itbis:f.itbis,estado:'Borrador'};setData({...data,cotizaciones:[...data.cotizaciones,n]});setShow(false)};const total=(x:Cotizacion)=>x.subtotal*(x.itbis?1.18:1);return <Module title="Cotizaciones" subtitle="Crea propuestas económicas y conviértelas en proyectos" action="Nueva cotización" onAction={()=>setShow(true)}>{show&&<FormCard title="Crear cotización" close={()=>setShow(false)}><FormGrid><Select label="Cliente" value={f.clienteId} onChange={v=>setF({...f,clienteId:v})} options={data.clientes.map(x=>[x.id,x.nombre])}/><Input label="Nombre del trabajo" value={f.proyecto} onChange={v=>setF({...f,proyecto:v})}/><Input label="Monto subtotal" type="number" value={f.subtotal} onChange={v=>setF({...f,subtotal:v})}/><label className="check"><input type="checkbox" checked={f.itbis} onChange={e=>setF({...f,itbis:e.target.checked})}/> Aplicar 18% ITBIS</label><TextArea label="Descripción / alcance" value={f.descripcion} onChange={v=>setF({...f,descripcion:v})}/></FormGrid><Save onClick={add}/></FormCard>}<Table heads={['Número','Fecha','Cliente / Trabajo','Estado','Subtotal','Total','Acciones']}>{data.cotizaciones.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td><b>{x.numero}</b></td><td>{x.fecha}</td><td><b>{data.clientes.find(c=>c.id===x.clienteId)?.nombre}</b><small>{x.proyecto}</small></td><td><select className="status" value={x.estado} onChange={e=>setData({...data,cotizaciones:data.cotizaciones.map(y=>y.id===x.id?{...y,estado:e.target.value as Cotizacion['estado']}:y)})}><option>Borrador</option><option>Enviada</option><option>Aprobada</option><option>Rechazada</option></select></td><td>{money(x.subtotal)}</td><td><b>{money(total(x))}</b></td><td><div className="actions"><button className="icon" title="Imprimir" onClick={()=>window.print()}><Printer size={17}/></button><Delete onClick={()=>setData({...data,cotizaciones:data.cotizaciones.filter(y=>y.id!==x.id)})}/></div></td></tr>)}</Table></Module>}

function Proyectos({data,setData,query}:{data:AppData;setData:(d:AppData)=>void;query:string}){const [show,setShow]=useState(false);const [f,setF]=useState({nombre:'',clienteId:data.clientes[0]?.id||'',direccion:'',monto:'',inicio:today(),entrega:'',estado:'Planificación'});const add=()=>{const n:Proyecto={id:uid('pro'),nombre:f.nombre,clienteId:f.clienteId,direccion:f.direccion,monto:Number(f.monto),inicio:f.inicio,entrega:f.entrega,estado:f.estado as Proyecto['estado'],avanceFisico:0};setData({...data,proyectos:[...data.proyectos,n]});setShow(false)};return <Module title="Proyectos" subtitle="Control técnico y financiero de cada trabajo" action="Nuevo proyecto" onAction={()=>setShow(true)}>{show&&<FormCard title="Crear proyecto" close={()=>setShow(false)}><FormGrid><Input label="Nombre del proyecto" value={f.nombre} onChange={v=>setF({...f,nombre:v})}/><Select label="Cliente" value={f.clienteId} onChange={v=>setF({...f,clienteId:v})} options={data.clientes.map(x=>[x.id,x.nombre])}/><Input label="Dirección" value={f.direccion} onChange={v=>setF({...f,direccion:v})}/><Input label="Monto contratado" type="number" value={f.monto} onChange={v=>setF({...f,monto:v})}/><Input label="Fecha inicio" type="date" value={f.inicio} onChange={v=>setF({...f,inicio:v})}/><Input label="Entrega estimada" type="date" value={f.entrega} onChange={v=>setF({...f,entrega:v})}/></FormGrid><Save onClick={add}/></FormCard>}<div className="cards">{data.proyectos.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).map(p=>{const cob=data.movimientos.filter(m=>m.tipo==='cobro'&&m.proyectoId===p.id).reduce((a,b)=>a+b.monto,0);const gas=data.movimientos.filter(m=>m.tipo==='gasto'&&m.proyectoId===p.id).reduce((a,b)=>a+b.monto,0);return <article className="project-card" key={p.id}><div className="pc-head"><span className="pill">{p.estado}</span><Delete onClick={()=>setData({...data,proyectos:data.proyectos.filter(x=>x.id!==p.id)})}/></div><h3>{p.nombre}</h3><p>{data.clientes.find(c=>c.id===p.clienteId)?.nombre} · {p.direccion}</p><div className="progress large"><i style={{width:`${p.avanceFisico}%`}}/></div><div className="pc-grid"><span>Avance<b>{p.avanceFisico}%</b></span><span>Contratado<b>{money(p.monto)}</b></span><span>Cobrado<b>{money(cob)}</b></span><span>Gastos<b>{money(gas)}</b></span></div><label className="range">Actualizar avance<input type="range" min="0" max="100" value={p.avanceFisico} onChange={e=>setData({...data,proyectos:data.proyectos.map(x=>x.id===p.id?{...x,avanceFisico:Number(e.target.value)}:x)})}/></label></article>})}</div></Module>}

function Bitacoras({data,setData,query}:{data:AppData;setData:(d:AppData)=>void;query:string}){const [show,setShow]=useState(false);const blank={fecha:today(),proyectoId:data.proyectos[0]?.id||'',clima:'Soleado',actividades:'',contratistas:'',equipos:'',materiales:'',incidencias:'',observaciones:'',avance:'0'};const [f,setF]=useState(blank);const add=()=>{const n:Bitacora={id:uid('bit'),...f,avance:Number(f.avance)};setData({...data,bitacoras:[...data.bitacoras,n]});setF(blank);setShow(false)};return <Module title="Bitácoras de obra" subtitle="Registra actividades, incidencias, recursos y avances diarios" action="Nueva bitácora" onAction={()=>setShow(true)}>{show&&<FormCard title="Registrar bitácora diaria" close={()=>setShow(false)}><FormGrid><Input label="Fecha" type="date" value={f.fecha} onChange={v=>setF({...f,fecha:v})}/><Select label="Proyecto" value={f.proyectoId} onChange={v=>setF({...f,proyectoId:v})} options={data.proyectos.map(x=>[x.id,x.nombre])}/><Input label="Clima" value={f.clima} onChange={v=>setF({...f,clima:v})}/><Input label="Avance del día (%)" type="number" value={f.avance} onChange={v=>setF({...f,avance:v})}/><TextArea label="Actividades realizadas" value={f.actividades} onChange={v=>setF({...f,actividades:v})}/><TextArea label="Contratistas presentes" value={f.contratistas} onChange={v=>setF({...f,contratistas:v})}/><TextArea label="Equipos utilizados" value={f.equipos} onChange={v=>setF({...f,equipos:v})}/><TextArea label="Materiales utilizados (solo registro)" value={f.materiales} onChange={v=>setF({...f,materiales:v})}/><TextArea label="Incidencias" value={f.incidencias} onChange={v=>setF({...f,incidencias:v})}/><TextArea label="Observaciones" value={f.observaciones} onChange={v=>setF({...f,observaciones:v})}/></FormGrid><Save onClick={add}/></FormCard>}<div className="timeline">{data.bitacoras.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).slice().reverse().map(b=><article className="log" key={b.id}><div className="datebox"><b>{b.fecha.slice(8,10)}</b><span>{b.fecha.slice(5,7)}/{b.fecha.slice(0,4)}</span></div><div className="log-body"><div className="log-head"><div><h3>{data.proyectos.find(p=>p.id===b.proyectoId)?.nombre}</h3><span>{b.clima} · Avance del día {b.avance}%</span></div><div className="actions"><button className="icon" onClick={()=>window.print()}><Printer size={17}/></button><Delete onClick={()=>setData({...data,bitacoras:data.bitacoras.filter(x=>x.id!==b.id)})}/></div></div><p><b>Actividades:</b> {b.actividades}</p>{b.incidencias&&<p><b>Incidencias:</b> {b.incidencias}</p>}<details><summary>Ver detalles completos</summary><p><b>Contratistas:</b> {b.contratistas||'—'}</p><p><b>Equipos:</b> {b.equipos||'—'}</p><p><b>Materiales:</b> {b.materiales||'—'}</p><p><b>Observaciones:</b> {b.observaciones||'—'}</p></details></div></article>)}</div></Module>}

function Movimientos({data,setData,tipo,query}:{data:AppData;setData:(d:AppData)=>void;tipo:'cobro'|'gasto';query:string}){const [show,setShow]=useState(false);const [f,setF]=useState({fecha:today(),proyectoId:data.proyectos[0]?.id||'',concepto:'',monto:'',metodo:'Transferencia'});const add=()=>{const n:Movimiento={id:uid('mov'),...f,monto:Number(f.monto),tipo};setData({...data,movimientos:[...data.movimientos,n]});setShow(false)};const items=data.movimientos.filter(x=>x.tipo===tipo&&JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));return <Module title={tipo==='cobro'?'Cobros y avances':'Gastos'} subtitle={tipo==='cobro'?'Control de todo lo recibido de los clientes':'Egresos por proyecto y gastos generales'} action={tipo==='cobro'?'Registrar cobro':'Registrar gasto'} onAction={()=>setShow(true)}>{show&&<FormCard title={tipo==='cobro'?'Nuevo cobro':'Nuevo gasto'} close={()=>setShow(false)}><FormGrid><Input label="Fecha" type="date" value={f.fecha} onChange={v=>setF({...f,fecha:v})}/><Select label="Proyecto" value={f.proyectoId} onChange={v=>setF({...f,proyectoId:v})} options={data.proyectos.map(x=>[x.id,x.nombre])}/><Input label="Concepto" value={f.concepto} onChange={v=>setF({...f,concepto:v})}/><Input label="Monto" type="number" value={f.monto} onChange={v=>setF({...f,monto:v})}/><Select label="Método" value={f.metodo} onChange={v=>setF({...f,metodo:v})} options={['Transferencia','Efectivo','Cheque','Tarjeta'].map(x=>[x,x])}/></FormGrid><Save onClick={add}/></FormCard>}<div className="summary-strip"><span>Total registrado</span><b>{money(items.reduce((a,b)=>a+b.monto,0))}</b></div><Table heads={['Fecha','Proyecto','Concepto','Método','Monto','Acciones']}>{items.slice().reverse().map(m=><tr key={m.id}><td>{m.fecha}</td><td>{data.proyectos.find(p=>p.id===m.proyectoId)?.nombre}</td><td><b>{m.concepto}</b></td><td>{m.metodo}</td><td><b>{money(m.monto)}</b></td><td><Delete onClick={()=>setData({...data,movimientos:data.movimientos.filter(x=>x.id!==m.id)})}/></td></tr>)}</Table></Module>}

function Facturas({data,setData,query}:{data:AppData;setData:(d:AppData)=>void;query:string}){const [show,setShow]=useState(false);const [f,setF]=useState({clienteId:data.clientes[0]?.id||'',proyectoId:data.proyectos[0]?.id||'',concepto:'',monto:'',pagado:'0'});const add=()=>{const monto=Number(f.monto),pagado=Number(f.pagado);const n:Factura={id:uid('fac'),numero:`FAC-${String(data.facturas.length+1).padStart(4,'0')}`,fecha:today(),clienteId:f.clienteId,proyectoId:f.proyectoId,concepto:f.concepto,monto,pagado,estado:pagado>=monto?'Pagada':pagado>0?'Parcial':'Pendiente'};setData({...data,facturas:[...data.facturas,n]});setShow(false)};return <Module title="Facturación" subtitle="Facturas de avance, recibos y balances pendientes" action="Nueva factura" onAction={()=>setShow(true)}>{show&&<FormCard title="Emitir factura" close={()=>setShow(false)}><FormGrid><Select label="Cliente" value={f.clienteId} onChange={v=>setF({...f,clienteId:v})} options={data.clientes.map(x=>[x.id,x.nombre])}/><Select label="Proyecto" value={f.proyectoId} onChange={v=>setF({...f,proyectoId:v})} options={data.proyectos.map(x=>[x.id,x.nombre])}/><Input label="Concepto" value={f.concepto} onChange={v=>setF({...f,concepto:v})}/><Input label="Total factura" type="number" value={f.monto} onChange={v=>setF({...f,monto:v})}/><Input label="Monto pagado" type="number" value={f.pagado} onChange={v=>setF({...f,pagado:v})}/></FormGrid><Save onClick={add}/></FormCard>}<Table heads={['Factura','Fecha','Cliente','Concepto','Total','Pagado','Balance','Estado','Acciones']}>{data.facturas.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td><b>{x.numero}</b></td><td>{x.fecha}</td><td>{data.clientes.find(c=>c.id===x.clienteId)?.nombre}</td><td>{x.concepto}</td><td>{money(x.monto)}</td><td>{money(x.pagado)}</td><td><b>{money(x.monto-x.pagado)}</b></td><td><span className={`pill ${x.estado.toLowerCase()}`}>{x.estado}</span></td><td><div className="actions"><button className="icon" onClick={()=>window.print()}><Printer size={17}/></button><Delete onClick={()=>setData({...data,facturas:data.facturas.filter(y=>y.id!==x.id)})}/></div></td></tr>)}</Table></Module>}

function Contratistas({data,setData,query}:{data:AppData;setData:(d:AppData)=>void;query:string}){const [show,setShow]=useState(false);const [f,setF]=useState({nombre:'',especialidad:'',telefono:'',rnc:'',montoContratado:'',pagado:'0',proyectoId:data.proyectos[0]?.id||''});const add=()=>{const n:Contratista={id:uid('con'),...f,montoContratado:Number(f.montoContratado),pagado:Number(f.pagado)};setData({...data,contratistas:[...data.contratistas,n]});setShow(false)};return <Module title="Contratistas" subtitle="Contratos, trabajos, pagos y balances" action="Nuevo contratista" onAction={()=>setShow(true)}>{show&&<FormCard title="Registrar contratista" close={()=>setShow(false)}><FormGrid><Input label="Nombre" value={f.nombre} onChange={v=>setF({...f,nombre:v})}/><Input label="Especialidad" value={f.especialidad} onChange={v=>setF({...f,especialidad:v})}/><Input label="Teléfono" value={f.telefono} onChange={v=>setF({...f,telefono:v})}/><Input label="RNC/Cédula" value={f.rnc} onChange={v=>setF({...f,rnc:v})}/><Select label="Proyecto" value={f.proyectoId} onChange={v=>setF({...f,proyectoId:v})} options={data.proyectos.map(x=>[x.id,x.nombre])}/><Input label="Monto contratado" type="number" value={f.montoContratado} onChange={v=>setF({...f,montoContratado:v})}/><Input label="Pagado" type="number" value={f.pagado} onChange={v=>setF({...f,pagado:v})}/></FormGrid><Save onClick={add}/></FormCard>}<Table heads={['Contratista','Especialidad','Proyecto','Contratado','Pagado','Pendiente','Acciones']}>{data.contratistas.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())).map(x=><tr key={x.id}><td><b>{x.nombre}</b><small>{x.telefono}</small></td><td>{x.especialidad}</td><td>{data.proyectos.find(p=>p.id===x.proyectoId)?.nombre}</td><td>{money(x.montoContratado)}</td><td>{money(x.pagado)}</td><td><b>{money(x.montoContratado-x.pagado)}</b></td><td><Delete onClick={()=>setData({...data,contratistas:data.contratistas.filter(y=>y.id!==x.id)})}/></td></tr>)}</Table></Module>}

function Caja({data,setData}:{data:AppData;setData:(d:AppData)=>void}){const ingresos=data.movimientos.filter(m=>m.tipo==='cobro').reduce((a,b)=>a+b.monto,0),gastos=data.movimientos.filter(m=>m.tipo==='gasto').reduce((a,b)=>a+b.monto,0);return <Module title="Caja y bancos" subtitle="Disponibilidad estimada y cuentas financieras"><div className="stats"><div className="stat"><span>Saldo inicial</span><b>{money(data.cuentas.reduce((a,b)=>a+b.saldoInicial,0))}</b></div><div className="stat"><span>Ingresos</span><b>{money(ingresos)}</b></div><div className="stat"><span>Egresos</span><b>{money(gastos)}</b></div><div className="stat"><span>Disponible estimado</span><b>{money(data.cuentas.reduce((a,b)=>a+b.saldoInicial,0)+ingresos-gastos)}</b></div></div><div className="cards">{data.cuentas.map(c=><article className="bank-card" key={c.id}><Landmark/><div><span>{c.tipo}</span><h3>{c.nombre}</h3><b>{money(c.saldoInicial)}</b></div></article>)}</div></Module>}

function Reportes({data}:{data:AppData}){const rows=data.proyectos.map(p=>{const cob=data.movimientos.filter(m=>m.tipo==='cobro'&&m.proyectoId===p.id).reduce((a,b)=>a+b.monto,0),gas=data.movimientos.filter(m=>m.tipo==='gasto'&&m.proyectoId===p.id).reduce((a,b)=>a+b.monto,0);return {...p,cob,gas,util:cob-gas,pend:p.monto-cob}});return <Module title="Reportes" subtitle="Resumen financiero por proyecto"><div className="report-actions"><button className="secondary" onClick={()=>window.print()}><Printer size={18}/> Imprimir / Guardar PDF</button></div><Table heads={['Proyecto','Contratado','Cobrado','Gastos','Por cobrar','Resultado de caja','Avance']}>{rows.map(x=><tr key={x.id}><td><b>{x.nombre}</b></td><td>{money(x.monto)}</td><td>{money(x.cob)}</td><td>{money(x.gas)}</td><td>{money(x.pend)}</td><td><b>{money(x.util)}</b></td><td>{x.avanceFisico}%</td></tr>)}</Table></Module>}
function Configuracion({data,setData}:{data:AppData;setData:(d:AppData)=>void}){return <Module title="Configuración" subtitle="Datos generales y mantenimiento del sistema"><div className="settings-grid"><section className="panel"><h3>Empresa</h3><label>Nombre comercial<input defaultValue="CONSTRUPLATA SRL"/></label><label>Moneda<input defaultValue="DOP - Peso dominicano"/></label><label>Impuesto predeterminado<input defaultValue="18% ITBIS"/></label><button className="primary">Guardar configuración</button></section><section className="panel danger"><h3>Datos de prueba</h3><p>Restablece la información inicial incluida para explorar la aplicación.</p><button className="secondary" onClick={()=>{if(confirm('¿Restablecer todos los datos?'))setData(seedData)}}>Restablecer datos</button><p className="muted">Para producción se recomienda conectar Supabase.</p></section></div></Module>}

function Module({title,subtitle,action,onAction,children}:{title:string;subtitle:string;action?:string;onAction?:()=>void;children:React.ReactNode}){return <><div className="module-head"><div><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button className="primary" onClick={onAction}><Plus size={18}/>{action}</button>}</div>{children}</>}
function FormCard({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <section className="form-card"><div className="panel-head"><h3>{title}</h3><button className="icon" onClick={close}><X size={18}/></button></div>{children}</section>}
function FormGrid({children}:{children:React.ReactNode}){return <div className="form-grid">{children}</div>}
function Input({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="wide">{label}<textarea value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Save({onClick}:{onClick:()=>void}){return <div className="save-row"><button className="primary" onClick={onClick}>Guardar registro</button></div>}
function Delete({onClick}:{onClick:()=>void}){return <button className="icon danger-btn" onClick={()=>confirm('¿Eliminar este registro?')&&onClick()}><Trash2 size={17}/></button>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Empty(){return <div className="empty">No hay registros todavía.</div>}
